# Language: Slovenian (CP852)
# Translated by Matej Horvat (http://matejhorvat.si/), last update 2013-06-04

#### This file is part of the FreeDOS HTML Help Viewer
#### and is licensed under its terms.

# Program Usage Screen Strings
1.0:FreeDOS pregledovalnik HTML pomoüi
1.1:Osnovne moßnosti
1.2:Prikaße pomoü o ßeljeni tÇmi.
1.3:Prikaße to sporoüilo.
1.4:Monokromatska barvna shema.
1.5:Uporabi alternativno barvno shemo
1.6:Uporabi ASCII znake namesto razÁirjenih.
1.7:Uporabi kodno stran nnn, namesto da bi jo poskusil zaznati.
1.8:Napredne moßnosti
1.9:Uporabi drugo pot pomoüi; üe ni doloüena nobena druga
1.10:datoteka, se uporabi index.htm.
1.11:Naloßi drugo datoteko kot index.htm relativno na pot pomoüi.
1.12:Ko pritisnete F1 oz. kliknete "pomoü o pomoüi", bo naloßena
1.13:ta datoteka. Privzeta je help.htm.
1.14:Okoljske spremenljivke
1.15:Imenik, ki vsebuje datoteke s pomoüjo
1.16:Sem dajte /M, /A, /F1, /F2, da jih nastavite za privzete.

#Error Message Strings
2.0:Ni bilo mogoüe rezervirati spomina
2.1:Neveljaven argument
2.2:Prosim, doloüite samo eno tÇmo
2.3:Ni mogoüe uporabiti /F in /M naenkrat
2.4:Vtipkajte "HELP /?" za navodila za uporabo.
2.5:Ni toünega zadetka za tÇmo
2.6:Ni bilo mogoüe najti tÇme
2.7:Notranja napaka pri spreminjanju velikosti
2.8:Ni mogoüe brati stisnjene datoteke
2.9:Ni mogoüe odpreti
2.10:Datoteka ZIP je prazna ali poÁkodovana
2.11:Ni bilo mogoüe najti te datoteke. Nalagam prvo datoteko v ZIP
2.12:Ni bilo mogoüe najti datoteke HTML v ZIP
2.13:Prosim, doloüite veljavno kodno stran
2.14:Doloüena kodna stran ni podprta
2.15:Podprte kodne strani so

#Menu Strings
#### HTML Help will truncate strings 3.0 and 3.1
#### if they exceed 14 characters.
3.0:Izhod
3.1:Pomoü o pomoüi
#### HTML Help will truncate strings 3.2-3.5
#### if they exceed 10 characters.
3.2:Nazaj
3.3:Naprej
3.4:Kazalo
3.5:IÁüi

#Button Label Strings
#### HTML Help will truncate strings 4.0-4.2
#### if they exceed 8 characters.
4.0:V redu
4.1:Prekliüi
4.2:Pomoü

#Status Bar Strings
5.0:IÁüem tÇmo...
5.1:Polno iskanje v teku...
5.2:(pritisnite Esc, da ga prekinete)

#Search Box Strings
#### HTML Help will truncate strings:
####    6.0      if it exceeds 35 characters;
####    6.1      if it exceeds 20 characters;
####    6.2-6.5  if they exceed 28 characters;
####    6.6-6.13 if they exceed 35 characters.
6.0:Iskanje po pomoüi
6.1:IÁüi besedilo:
6.2:loüi male in velike ürke
6.3:samo cele besede
6.4:polno iskanje
6.5:samo na tej strani
#Help on Search:
6.6:Razlaga
#Lines 6.7-6.9 describe "Search":
6.7:Polno iskanje:
6.8:PreiÁüe vse datoteke, naÁtete v
6.9:kazalu.
#Line 6.10 can be used if you need more room.
6.11:Samo na tej strani:
6.12:IÁüe le po trenutno odprtem
6.13:dokumentu.

#Search Results Strings
7.0:Rezultati iskanja
7.1:V datotekah, naÁtetih v kazalu,
# The following line, 7.2, is used as "Searched [FILENAME]"
7.2:V datoteki
# The following line, 7.3, is used as "for: [TEXT]"
7.3:je bilo iskano besedilo
7.4:Po rezultatih iskanja ne morete iskati.
7.5:Iskanje je bilo prekinjeno
7.6:Ni rezultatov
