# Language: Polish (MAZOVIA)
# Translated by Mateusz Viste
# Polish letters encoded in the MAZOVIA standard

#### This file is part of the FreeDOS HTML Help Viewer
#### and is licensed under its terms.

# Program Usage Screen Strings
1.0:PrzeglÜdarka plik¢w pomocy w systemie HTML dla FreeDOS
1.1:Opcje podstawowe
1.2:Wyûwietla pomoc na ten temat
1.3:Wyûwietla ten komunikat pomocy
1.4:Wymusza tryb czarno-biaíy
1.5:Ußywa fantazyjnego schematu kolor¢w
1.6:Ußywa ASCIIU zamiast rozszerzonego zestawu znak¢w
1.7:Wymusza ußycie strony kodowej nnn (domyûlnie wybierana automatycznie)
1.8:Opcje zaawansowane
1.9:Nadpisuje ûcießkë pomocy
1.10:jeûli nie okreûli sië ßadnego pliku, ußywany jest index.htm
1.11:úaduje inny plik niß index.htm ze ûcießki pomocy
1.12:Gdy ußytkownik wciûnie F1 lub kliknie na "pomoc o pomocy"
1.13:pomoc zaíaduje ten plik. Domyûlnie jest help.htm
1.14:Zmienne ûrodowiskowe
1.15:Katalog zawierajÜcy pliki pomocy
1.16:Wpisz /M, /A, F1, F2 tutaj aby byíy domyûlne

#Error Message Strings
2.0:Alokacja pamiëci niemoßliwa
2.1:Niepoprawny argument
2.2:Proszë podaç tylko jeden temat
2.3:Nie moßna ußyç /f razem z /m
2.4:Wpisz "HELP /?" dla instrukcji ußycia.
2.5:Nie odnaleziono pasujÜcych temat¢w
2.6:Nie moßna odnale¶ç tematu
2.7:BíÜd wewnëtrzny: Zmiana wielkoûci nie powiodía sië
2.8:Nie moßna odczytaç skompresowanego pliku
2.9:Nie moßna otworzyç
2.10:Archiwum zip jest puste lub uszkodzone
2.11:Nie moßna odnale¶ç tego pliku. úadowanie pierwszego pliku html z archiwum zip
2.12:Nie moßna odnale¶ç pliku html w archiwum zip
2.13:Podaj poprawnÜ stronë kodowÜ
2.14:Podana strona kodowa nie jest obsíugiwana
2.15:Obsíugiwane strony kodowe to

#Menu Strings
#### HTML Help will truncate strings 3.0 and 3.1
#### if they exceed 14 characters.
3.0:Wyjûcie
3.1:Pomoc o pomocy
#### HTML Help will truncate strings 3.2-3.5
#### if they exceed 10 characters.
3.2:Wstecz
3.3:Wprz¢d
3.4:Zawartoûç
3.5:Szukaj

#Button Label Strings
#### HTML Help will truncate strings 4.0-4.2
#### if they exceed 8 characters.
4.0:OK
4.1:Anuluj
4.2:Pomoc

#Status Bar Strings
5.0:Szukanie tematu...
5.1:Peíne wyszukiwanie w toku...
5.2:(NACIòNIJ ESC ABY PRZERWAï)...

#Search Box Strings
#### HTML Help will truncate strings:
####    6.0      if it exceeds 35 characters;
####    6.1      if it exceeds 20 characters;
####    6.2-6.5  if they exceed 28 characters;
####    6.6-6.13 if they exceed 35 characters.
6.0:Search Help
6.1:Szukany tekst:
6.2:rozr¢ßniaj duße/maíe litery
6.3:tylko peíne síowa
6.4:peíne wyszukiwanie
6.5:na tej stronie
#Help on Search:
6.6:Do czego síußy
#Lines 6.7-6.9 describe "Search":
6.7:peíne wyszukiwanie:
6.8:Szuka we wszystkich plikach
6.9:wymienionych na stronie.
#Line 6.10 can be used if you need more room.
6.11:na tej stronie:
6.12:Szuka tylko i wyíÜcznie
6.13:w otwartym dokumencie

#Search Results Strings
7.0:Wyniki wyszukiwania
7.1:Przeszukano wszystkie pliki wymienione na stronie
# The following line, 7.2, is used as "Searched [FILENAME]"
7.2:Szukano
# The following line, 7.3, is used as "for: [TEXT]"
7.3:dla
7.4:,Przykro mi, nie mogë przeszukiwaç wynik¢w.
7.5:U°YTKOWNIK PRZERWAú (nacisnÜí escape)
7.6:Brak wynik¢w
