#Translated by Mateusz Viste "Fox" / mateusz.viste@mail.ru
#Polish letters encoded in the MAZOVIA standard
#Homepage: http://www.the.killer.webpark.pl
#
# Help Message

0.0:Move
0.1:Przenosi plik/katalog w inne miejsce.
0.2:(C) 1997-2002 by Joe Cosentino
0.3:(C) 2003-2004 by Imre Leber
0.4:Skíadnia: MOVE
0.5:¶r¢dío1[, ¶r¢dío2[,...]] cel
0.6: ¶r¢dío      Nazwa pliku lub katalogu kt¢ry chcesz przenieûç
0.7: cel         Miejsce docelowe przeniesienia pliku(¢w)
0.8:          Likwiduje zapytanie o nadpisanie juß istniejÜcych plik¢w
0.9:             docelowych.
0.10:         Wymusza monit o potwierdzenie nadpisania juß istniejÜcych
0.11:             plik¢w docelowych.
0.12:          Sprawdza kaßdy plik pod kÜtem zgodnoûci z oryginaíem. W ten
0.13:             spos¢b mamy pewnoûç ße pliki docelowe i ¶r¢díowe sÜ
0.14:             identyczne.
0.15:Uwaga:
0.16:Tym poleceniem moßna takße przenosiç katalogi.

# Various messages

1.0:nie istnieje!
1.1:juß istnieje!
1.2:Nadpisaç plik
1.3:Problem w przenoszeniu katalogu
1.4:Problem w przenoszeniu pliku
1.5:Nieprawidíowy parametr
1.6:Nieprawidíowa specyfikacja napëdu ¶r¢díowego
1.7:Nieprawidíowy plik docelowy
1.8: nie istnieje jako katalog. Stworzyç go?
1.9:Nieprawidíowy plik ¶r¢díowy
1.10:Nie moßna stworzyç katalogu
1.11:Plik nie moße byç skopiowany na siebie samego
1.12:Nie moßna przenieûç pliku w katalog
1.13:Plik juß istnieje
1.14:Plik nie moße byç skopiowany na siebie samego
1.15:Dostëp odm¢wiony
1.16:Brak miejsca na dysku docelowym
1.17:Brak miejsca na dysku
1.18:Brak wymaganego parametru
1.19:Nieprawidíowe ¶r¢dío
1.20:òcießka ¶r¢díowa nie odnaleziona
1.21:òcießka ¶r¢díowa za díuga\n
1.22:òcießka docelowa za díuga\n
1.23:Nieprawidíowa specyfikacja napëdu docelowego\n
1.24:òcießka docelowa za díuga\n
1.25:Nie moßna otworzyç pliku ¶r¢díowego
1.26:Nie moßna stworzyç pliku docelowego
1.27:BíÜd zapisu do pliku docelowego
1.28:Nie moßna stworzyç katalogu
1.29:Brak miejsca na dysku docelowym

# Y/N/All/None; Simple messages

2.0:T
2.1:N
2.2:Wszystkie
2.3:Brak
2.4:ok
