# This is the translation file model for FreeDOS Password v0.50
#
#               Language: Polish
#               Codepage: 991 (Mazovia)
#
# Author of the translation: Mateusz Viste
#
# All spaces before text must be preserved and each line must not contain
# any space character at its end!
#
0.1:Ußytkownicy
0.2:Naleßy zdefiniowaç conajmniej jednego ußytkownika:
0.3:Login:
0.4:Hasío:
0.5:Ußytkownik
0.6:zostaí dodany
0.7: UWAGA! Osoba trzecia pr¢bowaía poprzednio sië zalogowaç.
0.8:        Po szczeg¢íy proszë zajrzeç do pliku log.
0.9: Naciûnij dowolny klawisz...
0.10:Dostëp wzbroniony!
0.11:Wprowad¶ login ußytkownika kt¢rego chcesz usunÜç:
0.12: Ußytkownik usuniëty.
0.13:nie odnaleziony!
0.14:Wprowad¶ ußytkownika kt¢rego chcesz dodaç:
0.15:Ußytkownik dodany.
0.16: Login
0.17:jest juß w ußyciu.
0.18: Opcje:
0.19: /adduser   Dodaje nowego ußytkownika do programu
0.20: /login     Logowanie
0.21: /remuser   Usuwa ußytkownika z programu
0.22:pomyûlnie sië zalogowaí
0.23:pr¢bowaí sië zalogowaç
0.24:zostaí usuniëty
