echo off
cls
echo.
echo.
echo.
echo.                **********************************************
echo.                *                                            *
echo.                *       WHEN RUNNING CHAOS ENGINE FOR        *
echo.                *     THE FIRST TIME, RUN INSTALL FIRST      *
echo.                *      TO CONFIGURE YOUR JOYSTICK AND        *
echo.                *               KEYBOARD.                    *
echo.                *                                            *
echo.                *     IF THIS IS NOT DONE, CHAOS ENGINE      *
echo.                *           MAY NOT WORK PROPERLY.           *
echo.                *                                            *
echo.                *        To skip this message in the         *
echo.                *           future, type: CEDEMO             *
echo.                *                                            *
echo.                **********************************************
echo.
echo.
pause
install
