
		    H&G SOFTWARE ORDERING INFORMATION

You can order directly from H&G Software (check or money order only) or
from Public Software Library with your MC, Visa, AmEx or Discover card by
calling 1-800-242-4PSL (from overseas 713-524-6394), by FAX to 713-524-6398
or by CompuServe to 71355,470.  THESE NUMBERS ARE FOR ORDERING ONLY.  To
facilitate ordering, note the program's Part # before phoning.

H&G Software can NOT be reached at those numbers.  To contact H&G Software
to order by check, for information about dealer pricing, upgrades, volume
discounts, site licensing, the status of shipment of the product, the
latest version number, for technical information, or to discuss returns,
write H&G Software at

			H&G Software
			P.O. Box 3013
			Vancouver, B.C.
			Canada  V6B 3X5

H&G Software can now be reached on Compuserve, please send enquiries to:

	Reidar Gresseth
	Compuserve		73042,3653
	Internet		73042.3653@compuserve.com

NOTE: Please provide correct postage to Canada.  The Canadian postal
service will return letters with incorrect postage to the sender.

H&G Software offers a discount schedule for those who wish to order
multiple licenses.  Please refer to the following tables:


    Axel Desktop	VOLUME GROUP	|    PRICE PER UNIT
			1-5		|	$35.00 US
			6-24		|	$30.00 US
			25-99		|	$25.00 US
			100-299		|	$20.00 US
			300+		|	$15.00 US


    Explosiv Deluxe	VOLUME GROUP	|    PRICE PER UNIT
			1-5		|	$30.00 US
			6-24		|	$25.00 US
			25-99		|	$20.00 US
			100-299		|	$15.00 US
			300-999		|	$12.50 US
			1000+		|	$10.00 US


    Explosiv		VOLUME GROUP	|    PRICE PER UNIT
			1-24		|	$20.00 US
			25-99		|	$17.50 US
			100-299		|	$15.00 US
			300-999		|	$12.50 US
			1000+		|	$10.00 US


For a special discount, you can order Explosiv Deluxe and Axel Desktop
together for a total registration fee of $50.00 US + $10.00 S&H.  NOTE
that this offer does NOT apply to credit card orders, it only available
for orders sent directly to H&G Software.

			H&G SOFTWARE ORDER FORM

Name ________________________________________________________________

Address _____________________________________________________________

        _____________________________________________________________

City ____________________________ State _____________________________

Country _________________________ Zip Code __________________________

Phone (_________) ___________________________________


Please select preferred disk size (3.5" high density is the default) :

[  ] 3.5" 1.44M    [  ] 3.5" 720K    [  ] 5.25"	1.2M    [  ] 5.25" 360K

To order you must both licence the software and purchase a disk ( that
is, you must fill in BOTH sections 1 and 2 ).  Sum the values in the
TOTAL column in both sections and enter the amount in section 3, this
is the final cost of the program.  You must purchase one licence for
each computer or workstation that will be running the program ( but you
do not need to order more than a single disk ). 

1. LICENCING OR REGISTRATION CHARGES:
					QUANTITY     PRICE         TOTAL

  Axel Desktop Utilities (Part # 11381)  ______  X  $35.00 US  =  ________

  Explosiv Screen Saver	(Part # 10834)   ______  X  $20.00 US  =  ________

  Explosiv Deluxe (Part # 11380)	 ______  X  $30.00 US  =  ________

Upgrading from:

  Explosiv 1.x to Explosiv 3.x		 ______  X  $15.00 US  =  ________

  Explosiv 2.x/3.x to Explosiv Deluxe	 ______  X  $10.00 US  =  ________

  Explosiv 1.x to Explosiv Deluxe        ______  X  $25.00 US  =  ________

Note that Explosiv Deluxe includes the latest version of the Explosiv.


2. SHIPPING AND HANDLING CHARGES:
					QUANTITY     PRICE         TOTAL

  Axel disk and manual			 ______  X  $5.00 US  =   ________

  Explosiv family disk and manual        ______  X  $5.00 US  =   ________


3. TOTAL COST:

Sum the values in TOTAL			     Amount Enclosed $ ________ US


All prices are quoted in US funds.  Equivalent values in Canadian funds
are also acceptable ( i.e., Amount multiplied by US to CA exchange rate ).
