     ==================================================================
     APOGEE SOFTWARE ORDER FORM - FAX SHEET  (Fax number: 214-278-4670)
                                PAGE 1 OF 2
     ==================================================================

                  *** Mark all games you wish to order ***

[ ] Death Rally, Top down 3D racing with combat & gore! (CD Only)  ($29.95)
[ ] Xenophage, Fierce Fighting Fun for your CD-ROM Only!           ($34.95)
[ ] Realms of Chaos, Disk or CD-ROM Version - VGA arcade/action!   ($24.95)
[ ] Rise of the Triad, CD-ROM Version - Includes PowerPack         ($34.95)
[ ] Rise of the Triad, Disk Version - Full game with 30+ levels    ($29.95)
[ ] Rise of the Triad, PowerPack - Add Xtras for Disk Version ONLY ($10.00)
[ ] Rise of the Triad, Site License CDROM Version Save up to $295! ($89.95)
[ ] Rise of the Triad Extreme, CD Addon Pack. Requires Reg Version ($19.95)
[ ] Boppin' - VGA arcade/puzzle game w/160 levels & level editor!  ($29.95)
[ ] Boppin' (budget edition) - Only 80 levels and no level editor  ($19.95)
[ ] Wacky Wheels -- VGA 3D competitive racing game with 21 tracks  ($24.95)
[ ] Wacky Wheels "Upgrade Edition" -- With 42 total tracks!        ($34.95)
[ ] Hocus Pocus -- VGA parallaxing platform action/puzzle game!    ($24.95)
[ ] Planet Strike -- 3D Action, sequel to original Blake Stone     ($24.95)
[ ] Blake Stone: Aliens of Gold - Futuristic 3D action, 66 levels! ($29.95)
[ ] Raptor: Call of the Shadows - Best VGA shooter ever on the PC! ($34.95)
[ ] Alien Carnage - Technically superb VGA jetpack game            ($19.95)
[ ] Duke Nukem II -- New VGA explosive action game                 ($34.95)
[ ] Duke Nukem I (the original) -- Non-stop pure action!           ($29.95)
[ ] Cosmo's Cosmic Adventure - Help rescue Cosmo's parents         ($34.95)
[ ] Wolfenstein 3-D All SIX EPISODES "Wolf-Pack"                   ($49.95)
[ ] Wolfenstein 3-D Hint Book (with all maps, story and secrets)   ($10.00)
[ ] Wolfenstein 3-D "Spear of Destiny" - A Commercial Wolf3D game  ($29.95)
[ ] Cmdr. Keen: Vorticons - The original Keen from Id Software     ($29.95)
[ ] Cmdr. Keen: Goodbye Galaxy - Id's sequel to the classic        ($34.95)
[ ] Cmdr. Keen: Aliens Ate My Baby Sitter - A commercial Keen game ($34.95)

[ ] other _________________________________________________________________


          *** THE FOLLOWING COMBO OFFERS WILL SAVE YOU BIG BUCKS! ***

[ ] Blast 'em COMBO:  Raptor & Major Stryker (SAVE $15!)           ($49.95)
[ ] Duke COMBO:  Both Duke Nukem I & Duke Nukem II (SAVE $15!)     ($49.95)
[ ] Duke/Cosmo COMBO:  Both Duke Nukems PLUS Cosmo (SAVE $30!)     ($69.95)
[ ] Kid COMBO:  Word Rescue & Math Rescue (SAVE $20!)              ($39.95)
[ ] Cmdr. Keen V/G COMBO:  Vorticons & Goodbye Galaxy (SAVE $15!)  ($49.95)
[ ] Cmdr. Keen G/A COMBO:  Goodbye Galaxy & Aliens (SAVE $10!)     ($59.95)
[ ] Cmdr. Keen SUPER COMBO:  ALL SIX KEEN EPISODES! (SAVE $30!)    ($69.95)

DISK SIZE: [ ] 3.5" 1.44M  [ ] 3.5" 720K  [ ] 5.25" 1.2M
     NOTE: 360k not supported; VGA games only available on High Density

GRAPHICS:  [ ] SVGA  [ ] VGA  [ ] EGA  [ ] Other:__________________________

COMPUTER:  [ ] PENTIUM/586  [ ] 486  [ ] 386  [ ] 286  [ ] Other:__________

SOUND CARD:  [ ] Sound Blaster (SB)  [ ] SB Pro  [ ] SB 16  [ ] Ad Lib

             [ ] PAS 16  [ ] GUS  [ ] None  [ ] Other:_____________________

                             --- continued ---

     ==================================================================
     APOGEE SOFTWARE ORDER FORM - FAX SHEET  (Fax number: 214-278-4670)
                                PAGE 2 OF 2
     ==================================================================

Name (please print)________________________________________________________

Address ___________________________________________________________________

Address ___________________________________________________________________

City _______________________ St./Prov. _________________ ZIP/Code _________

Country (if not USA) ____________________ Phone/Fax _______________________

SHIPPING [ ] USA: $5. Each additional item add $1.
CHARGES: [ ] Canada & Mexico: $6. Each additional item add $1.
         [ ] All other countries: $8. Each addtl. game add $2; shirts $4.

Total payment: $______________  (TX residents MUST add correct sales tax.)
Note: Payment must be in U.S. dollars and drawn against a U.S. bank.
      Please do not send cash!

Payment: [ ] Visa [ ] MasterCard [ ] Discover [ ] Check [ ] Money Order

Card number: ______________________________________________________________

Expiration date: _____/_____ (MM/YY)  Signature: __________________________

Mail to:  Apogee Software, Ltd.      Order: 1-800-APOGEE1  (1-800-276-4331)
          P.O. Box 496389            Phone: (214) 278-5655 (Foreign orders)
          Garland, TX 75049-6389     Visa, MasterCard, Discover welcome!

Thank you for your order!  Make checks payable to "Apogee".  Allow up to
two weeks for delivery.  All prices subject to change without notice.
All items subject to availability.

Where do you get or buy Apogee shareware games (check favorite two only)?

  [ ] Apogee's home BBS:  The Software Creations BBS
  [ ] CompuServe
  [ ] America Online
  [ ] Other BBS -- Please write name:
  [ ] Shareware catalog -- Please write name:
  [ ] Work, a friend or a relative
  [ ] Retail store, off a rack, in a box or other simple packaging
  [ ] CD-ROM disk
  [ ] Other:_______________________________________________________________

What do you like/dislike about Apogee, our games, business with us, etc.?

___________________________________________________________________________

___________________________________________________________________________

___________________________________________________________________________

Thank you!
